#### Fill in the xxxx in this example with your values ####

version: '3'

services:
  osm2pgrouting: &osm2pgrouting
    image: xxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/osm2pgrouting:latest
    build: .
    env_file:
      - ./.env
    ports:
      - 80:80
    logging:
      driver: awslogs
      options: 
        awslogs-group: xxxx_xxxx
        awslogs-region: us-east-1
        awslogs-stream-prefix: xxx_xxx_xxx
